service: user-service

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    USERS_TABLE: Users
    DYNAMODB_ENDPOINT: http://localhost:8000
    JWT_SECRET: your_jwt_secret_key

functions:
  api:
    handler: src/adapters/lambdaHandler.handler
    timeout: 90
    events:
      - http:
          path: /register
          method: post
      - http:
          path: /login
          method: post
      - http:
          path: /verify-token
          method: get

resources:
  Resources:
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: cpf
            AttributeType: S
        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
